### ISSUE TITLE
Aufruf der Workflow UI führt zu TLS Handshake Fehler

### ISSUE THREAD

**Issue by KillerCodeMonkey** [gematik/KOB-Testsuite#15]
Wie im andere Issue beschrieben, kann ich auf Ubuntu 24.0.4 oder Ubuntu 22.0.4 die Tests nicht starten.

Der Fehler kommt mit Docker und direktem mvn Aufruf.

Der Aufruf von 
```SH
sudo mvn clean verify -Dcucumber.filter.tags=@IBM
```

Ohne `sudo` gehts hier standardmäßig nicht, weil man nicht als ordinärer User Services auf den Default Ports 80/443 starten darf.

führt zu folgendem Log, sobald man die Workflow UI aufruft:
[start.log](https://github.com/user-attachments/files/17992833/start.log)

```SH
Apache Maven 3.8.7
Java version: 21.0.5, vendor: Ubuntu, runtime: /usr/lib/jvm/java-21-openjdk-amd64
Default locale: de_DE, platform encoding: UTF-8
OS name: "linux", version: "6.11.0-107011", arch: "amd64", family: "unix"
```

kob.yml:

```yml
kob:
  # Die URL der Testtreiberschnittstelle des Primärsystems
  psurl: "http://localhost:8080"
  # Die URL der Mock-Aktensysteme. Standard ist 127.0.0.1, für docker-runs sollte host.docker.internal verwendet werden.
  asurl: "https://localhost:8443"
  # Soll die Testtreiberschnittstelle des Primärsystems verwendet werden?
  # Wenn false, dann werden in der WebUI Nachrichten angezeigt, die
  # beschreiben, was der Tester im Primärsystem machen soll.
  useTestdriverApi: false
  # Soll der Test headless, also ohne visuelle Überwachung im Browser, durchgeführt werden?
  useBrowser: true
  # Die KVNR, mit welcher die KOB durchgeführt werden soll.
  kvnrIbm: "X110616354"
  kvnrRise: "X110610882"
  # Welcher Typ von EML soll heruntergeladen werden ('XHTML', 'PDF', 'FHIR')
  emltype: "XHTML"

  testsuite:
    # Die Tags, die für die Ausführung der Testsuite verwendet werden sollen. "@KOB" führt die verpflichtenden KOB-Tests aus.
    tests: "@KOB"

  ##################################################################################
  # Detailkonfigurationen
  ##################################################################################
  # Soll der Browser gestartet werden? (true/false) Docker-Compose deaktiviert diese Option,
  # daher sollte diese Eigenschaft immer korrekt sein.
  startBrowser: true
  # Polling für die Testtreiber-API.
  polling:
    timeoutInSeconds: 120
    intervalInMilliseconds: 500

```

Die beiden routen in der `/etc/hosts` sind gesetzt und können angepingt werden. Zeigen, wie gewünscht, auf 127.0.0.1.

Es wird kein weiterer Proxy genutzt und keine Firewall ist aktiv.
