### ISSUE TITLE
0.6.3 Nutzung mit Docker führt zu Connection refused Fehler

### ISSUE THREAD

**Issue by KillerCodeMonkey** [gematik/KOB-Testsuite#7]
Ich habe eben die v0.6.3 abgerufen und gestartet.

Leider starten die Test in der Web-UI bei mir dann nicht.

Wenn ich mir die Request in der Web-UI anschaue steht über all folgendes:
```SH
Connection refused: host.docker.internal/127.0.0.1:8443
```

Mein Terminal zeigt ein paar Infos dazu an:

```SH
kob-testsuite  | 11:20:11.434 [MockServer-local_tiger_proxy-workerEventLoop5] INFO  d.g.t.t.m.n.HttpRequestHandler - Opening Proxy Channel, enabling SSL for 10.30.19.135:443
kob-testsuite  | 11:20:11.436 [MockServer-local_tiger_proxy-workerEventLoop5] INFO  d.g.t.t.m.n.p.r.RelayConnectHandler - Adding SSL Handler in RelayConnectHandler.channelRead
kob-testsuite  | 11:20:11.438 [HttpClient-8-Worker-2] INFO  o.b.j.p.ProvTlsClient - [client #61 @69dab28e] opening connection to 10.30.19.135:443
kob-testsuite  | 11:20:11.445 [MockServer-local_tiger_proxy-workerEventLoop5] INFO  o.b.j.p.ProvTlsClient - [client #62 @57a90e4c] opening connection to 10.30.19.135:443
kob-testsuite  | 11:20:11.446 [MockServer-local_tiger_proxy-workerEventLoop5] INFO  d.g.t.t.m.s.t.NettySslContextFactory - Creating new server SSL context for 10.30.19.135
kob-testsuite  | 11:20:11.447 [MockServer-local_tiger_proxy-workerEventLoop5] INFO  d.g.t.t.m.s.t.NettySslContextFactory - Using Server Certificate 'C=DE, ST=Berlin, L=Berlin, O=Gematik, CN=localhost', issued by 'CN=ca, OU=Gematik Patient Team, O=Gematik, L=State, ST=City, C=Country'
kob-testsuite  | 11:20:11.450 [MockServer-local_tiger_proxy-workerEventLoop7] INFO  d.g.t.t.m.s.t.NettySslContextFactory - Using existing server SSL context for null
kob-testsuite  | 11:20:11.451 [MockServer-local_tiger_proxy-workerEventLoop5] INFO  o.b.j.p.ProvTlsServer - [server #63 @60e97a14] accepting connection from (unknown):(unknown)
kob-testsuite  | 11:20:11.451 [MockServer-local_tiger_proxy-workerEventLoop7] INFO  o.b.j.p.ProvTlsServer - [server #64 @743256cc] accepting connection from (unknown):(unknown)
kob-testsuite  | 11:20:11.467 [MockServer-local_tiger_proxy-workerEventLoop5] INFO  o.b.j.p.ProvTlsServer - [server #63 @60e97a14] established connection with (unknown):(unknown)
kob-testsuite  | 11:20:11.468 [MockServer-local_tiger_proxy-workerEventLoop5] INFO  d.g.t.t.p.TigerProxyMasterSecretListener - Intercepted master secret, writing to file target/tlsSecrets.txt
kob-testsuite  | 11:20:11.469 [MockServer-local_tiger_proxy-workerEventLoop7] INFO  o.b.j.p.ProvTlsServer - [server #64 @743256cc] established connection with (unknown):(unknown)
kob-testsuite  | 11:20:11.469 [MockServer-local_tiger_proxy-workerEventLoop7] INFO  d.g.t.t.p.TigerProxyMasterSecretListener - Intercepted master secret, writing to file target/tlsSecrets.txt
kob-testsuite  | 11:20:11.470 [HttpClient-8-Worker-2] INFO  o.b.j.p.ProvTlsClient - [client #61 @69dab28e] established connection with 10.30.19.135:443
kob-testsuite  | 11:20:11.470 [MockServer-local_tiger_proxy-workerEventLoop5] INFO  o.b.j.p.ProvTlsClient - [client #62 @57a90e4c] established connection with 10.30.19.135:443
kob-testsuite  | 11:20:11.470 [HttpClient-8-Worker-2] INFO  d.g.t.t.p.TigerProxyMasterSecretListener - Intercepted master secret, writing to file target/tlsSecrets.txt
kob-testsuite  | 11:20:11.470 [MockServer-local_tiger_proxy-workerEventLoop5] INFO  d.g.t.t.p.TigerProxyMasterSecretListener - Intercepted master secret, writing to file target/tlsSecrets.txt
kob-testsuite  | 11:20:11.477 [http-nio-9011-exec-3] INFO  d.g.t.t.p.c.TigerWebUiController - Returning 2 messages (2 in menu, 2 filtered) of total 30
kob-testsuite  | 11:20:11.477 [MockServer-local_tiger_proxy-workerEventLoop7] INFO  d.g.t.t.p.h.AbstractTigerRouteCallback - Received HTTPS HEAD / Host: '10.30.19.135' User-Agent: 'Java-http-client/17.0.13' Request-Length: 0 bytes => https://host.docker.internal:8443
kob-testsuite  | 11:20:11.480 [MockServer-local_tiger_proxy-workerEventLoop8] INFO  d.g.t.t.m.h.HttpClientInitializer - Adding SSL Handler in HttpClientInitializer.initChannel
kob-testsuite  | 11:20:11.482 [MockServer-Scheduler2] INFO  d.g.t.t.p.h.AbstractTigerRouteCallback - Exception during handling of request HTTPS HEAD  Host: '10.30.19.135' User-Agent: 'Java-http-client/17.0.13' Request-Length: 0 bytes
kob-testsuite  | io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: host.docker.internal/127.0.0.1:8443
kob-testsuite  | Caused by: java.net.ConnectException: Connection refused
kob-testsuite  |        at java.base/sun.nio.ch.Net.pollConnect(Native Method)
kob-testsuite  |        at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:672)
kob-testsuite  |        at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:946)
kob-testsuite  |        at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:336)
kob-testsuite  |        at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:339)
kob-testsuite  |        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:776)
kob-testsuite  |        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
kob-testsuite  |        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
kob-testsuite  |        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
kob-testsuite  |        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:994)
kob-testsuite  |        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
kob-testsuite  |        at java.base/java.lang.Thread.run(Thread.java:840)
kob-testsuite  | 11:20:11.492 [MockServer-local_tiger_proxy-workerEventLoop7] INFO  o.b.j.p.ProvTlsServer - [server #64 @743256cc] disconnected from (unknown):(unknown)
kob-testsuite  | 11:20:11.494 [MockServer-local_tiger_proxy-workerEventLoop5] INFO  o.b.j.p.ProvTlsClient - [client #62 @57a90e4c] disconnected from 10.30.19.135:443
kob-testsuite  | 11:20:11.499 [MockServer-local_tiger_proxy-workerEventLoop5] INFO  o.b.j.p.ProvTlsServer - [server #63 @60e97a14] disconnected from (unknown):(unknown)
kob-testsuite  | 11:20:11.501 [HttpClient-8-Worker-2] INFO  o.b.j.p.ProvTlsClient - [client #61 @69dab28e] disconnected from 10.30.19.135:443
```

Meine KOB.yml
```YML
kob:
  # Die URL der Testtreiberschnittstelle des Primärsystems
  psurl: "http://localhost:8080"
  # Die URL der Mock-Aktensysteme. Standard ist 127.0.0.1, für docker-runs sollte host.docker.internal verwendet werden.
  # asurl: "https://localhost:8443"
  asurl: "host.docker.internal"
  # Soll die Testtreiberschnittstelle des Primärsystems verwendet werden?
  # Wenn false, dann werden in der WebUI Nachrichten angezeigt, die
  # beschreiben, was der Tester im Primärsystem machen soll.
  useTestdriverApi: false
  # Soll der Test headless, also ohne visuelle Überwachung im Browser, durchgeführt werden?
  useBrowser: true
  # Die KVNR, mit welcher die KOB durchgeführt werden soll.
  kvnrIbm: "X110616354"
  kvnrRise: "X110610882"
  # Welcher Typ von EML soll heruntergeladen werden ('XHTML', 'PDF', 'FHIR')
  emltype: "XHTML"

  testsuite:
    # Die Tags, die für die Ausführung der Testsuite verwendet werden sollen. "@KOB" führt die verpflichtenden KOB-Tests aus.
    tests: "@KOB"

  ##################################################################################
  # Detailkonfigurationen
  ##################################################################################
  # Soll der Browser gestartet werden? (true/false) Docker-Compose deaktiviert diese Option,
  # daher sollte diese Eigenschaft immer korrekt sein.
  startBrowser: true
  # Die RootCa, die der Tiger-Proxy verwenden soll. Der Standardwert ist "ca.p12;changeit".
  # Eigene Zertifikate können hinterlegt werden. Als Format sollte PKCS12 verwendet werden,
  # das Passwort kann nach einem Semikolon angegeben werden. Details können hier gefunden werden:
  # https://gematik.github.io/app-Tiger/Tiger-User-Manual.html#configuring-pki-identities-in-tiger-proxys-tls-section
  rootCa: ca.p12;changeit
  # Polling für die Testtreiber-API.
  polling:
    timeoutInSeconds: 120
    intervalInMilliseconds: 500

```

Routen in meiner `/etc/hosts` sind gesetzt für beide fqdm.

```
# ePA testsuite routing
127.0.0.1    epa-as-1.dev.epa4all.de
127.0.0.1    epa-as-2.dev.epa4all.de
```

Ich nutze Ubuntu 22.04 und für IBM konnten die Tests mit der v0.6.2 erfolgreich durchgeführt werden.
